name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "59 23 * * *"
 
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN_ID }}
  CID: ${{ secrets.CID }}
  DEV_TARBALL_VARIANT: _usrmerge
  ROOTFS_URL: "https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz"
  OTA_CHANNEL: "20.04/arm64/android9plus/stable"
  
jobs:
  BuildKernel:
    environment: TOKEN
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3        
      - name: build kernel
        run: |
          fmt=`date +%d\.%m\.%y_%r | sed 's/:/./g;s/ PM/.PM/g;s/ AM/.AM/g;s/ IST//g'`  
          export fmt=`date +%d\.%m\.%y_%r | sed 's/:/./g;s/ PM/.PM/g;s/ AM/.AM/g;s/ IST//g'`
          sudo apt update
          sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python
          sudo wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
          sudo chmod +x /usr/bin/mkbootimg
          git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-10-focal build
          sudo -s ./build/build.sh
          zip -r9 kernel-${fmt}-lavender.zip out/*
          ls kernel*.zip
          export OWO=$(ls kernel*-lavender.zip)
          curl -F document=@$OWO "https://api.telegram.org/bot"$TOKEN"/sendDocument" -F chat_id="$CID" -F "disable_web_page_preview=true" -F "parse_mode=html"
        
      - name: bootimg
        uses: actions/upload-artifact@master
        with:
          name: bootimg
          path: out/*
          
  BuildSystem:
      runs-on: ubuntu-20.04   
      steps:
        - uses: actions/checkout@v3
        - name: make systemimg
          run: |
              fmt=`date +%d\.%m\.%y_%r | sed 's/:/./g;s/ PM/.PM/g;s/ AM/.AM/g;s/ IST//g'`
              export fmt=`date +%d\.%m\.%y_%r | sed 's/:/./g;s/ PM/.PM/g;s/ AM/.AM/g;s/ IST//g'`
              sudo apt update
              sudo apt install git img2simg jq sudo wget xz-utils android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
              sudo ln -sf python2.7 /usr/bin/python
               sudo wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
              sudo chmod +x /usr/bin/mkbootimg
              sudo -s git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-10-focal build
              sudo -s ./build/build.sh
              DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
              sudo -s ./build/fetch-and-prepare-latest-ota.sh "$OTA_CHANNEL" "$DEVICE" ota
              mkdir -p out
              sudo -s ./build/system-image-from-ota.sh ota/ubuntu_command out
              
        - name: upload systemimg
          uses: actions/upload-artifact@master
          with:
              name: ubuntuimg
              path: |
               out/*
              
  BuildSystemDevel:
      runs-on: ubuntu-20.04 
      steps:
        - uses: actions/checkout@v3
        - name: make systemimg
          run: |
              sudo apt update
              sudo apt install git img2simg jq sudo wget xz-utils android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
              sudo ln -sf python2.7 /usr/bin/python
               sudo wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
              sudo chmod +x /usr/bin/mkbootimg
              sudo -s git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-10-focal build
              sudo -s ./build/build.sh
              DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
              sudo -s ./build/fetch-and-prepare-latest-ota.sh "$OTA_CHANNEL" "$DEVICE" ota
              mkdir -p out
              sudo -s ./build/system-image-from-ota.sh ota/ubuntu_command out
              sudo -s ./build/prepare-fake-ota.sh out/device_${DEVICE}$DEV_TARBALL_VARIANT.tar.xz ota
              mkdir -p out
              sudo -s ./build/system-image-from-ota.sh ota/ubuntu_command out
    
        - name: upload deveimg
          uses: actions/upload-artifact@master
          with:
              name: ubuntuimgdevel
              path: |
               out/boot.img
               out/dtbo.img
               out/system.img
